[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimization = true
optimizer_runs = 200
via_ir = true

[profile.coverage]
via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 80
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
